services:
  - type: web
    name: safechain-ai-support
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ai_support.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: safechain-ai-support.onrender.com
    disk:
      name: media-storage
      mountPath: /opt/render/project/src/media
      sizeGB: 1 