# Generated by Django 5.1.6 on 2025-06-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='intent_category',
            field=models.CharField(choices=[('billing', 'Billing/Payment'), ('technical', 'Technical Support'), ('account', 'Account Issues'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feature_request', 'Feature Request')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='requires_pop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='resolution_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user_satisfaction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
