# Generated by Django 5.0.2 on 2025-06-18 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ai_recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='collected_documents',
            field=models.ManyToManyField(blank=True, to='core.proofofpayment'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='next_admin_action',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='required_documents',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='intent_category',
            field=models.CharField(choices=[('billing', 'Billing/Payment'), ('technical', 'Technical Support'), ('account', 'Account Issues'), ('general', 'General Inquiry'), ('complaint', 'Complaint'), ('feature_request', 'Feature Request'), ('deposit_confirmation', 'Deposit Confirmation'), ('withdrawal_processing', 'Withdrawal Processing'), ('investment_verification', 'Investment Verification'), ('tier_upgrade', 'Tier Upgrade'), ('referral_verification', 'Referral Verification')], default='general', max_length=25),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('waiting_for_documents', 'Waiting for Documents'), ('ready_for_admin', 'Ready for Admin Review')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('deposit_confirmation', 'Deposit Confirmation'), ('withdrawal_processing', 'Withdrawal Processing'), ('investment_verification', 'Investment Verification'), ('payment_verification', 'Payment Verification'), ('account_verification', 'Account Verification'), ('tier_upgrade', 'Tier Upgrade Request'), ('referral_verification', 'Referral Verification'), ('general_support', 'General Support')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('requires_more_info', 'Requires More Information')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('required_documents', models.JSONField(default=list)),
                ('additional_info_required', models.JSONField(default=list)),
                ('ai_analysis', models.TextField(blank=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('risk_assessment', models.CharField(default='low', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('collected_documents', models.ManyToManyField(blank=True, to='core.proofofpayment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supportticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adminreport'),
        ),
    ]
