# Generated by Django 5.0.2 on 2025-06-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_supportticket_ai_recommendation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('waiting_for_documents', 'Waiting for Documents'), ('ready_for_admin', 'Ready for Admin Review'), ('waiting_for_admin', 'Waiting for Admin Review')], default='pending', max_length=25),
        ),
    ]
