# Generated by Django 5.0.2 on 2025-06-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_supportticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminreport',
            name='report_type',
            field=models.CharField(choices=[('deposit_confirmation', 'Deposit Confirmation'), ('withdrawal_processing', 'Withdrawal Processing'), ('investment_verification', 'Investment Verification'), ('payment_verification', 'Payment Verification'), ('account_verification', 'Account Verification'), ('tier_upgrade', 'Tier Upgrade Request'), ('referral_verification', 'Referral Verification'), ('general_support', 'General Support'), ('user_confirmed_issue', 'User Confirmed Issue')], max_length=50),
        ),
    ]
