# SafeChain AI Knowledge Base
# This file contains comprehensive information about SafeChain AI for the AI assistant

SAFECHAIN_KNOWLEDGE = {
    "company_info": {
        "name": "SafeChain AI",
        "tagline": "Grow Your Wealth with SafeChain AI",
        "description": "Secure, smart, and automated investing — starting from just R50.",
        "website": "https://safechain-7o0q.onrender.com",
        "email": "Shadowman@gmail.com",
        "status": "Live"
    },
    
    "statistics": {
        "investors_joined": "10,000+",
        "total_payouts": "R5M+",
        "ai_strategies": "15",
        "trusted_users": "2+"
    },
    
    "investment_tiers": [
        {
            "name": "Big Jumbo",
            "investment": "R50.00",
            "duration": "1 days",
            "return": "R100.00",
            "description": "Quick investment with fast returns"
        },
        {
            "name": "Big Fish", 
            "investment": "R200.00",
            "duration": "5 days",
            "return": "R400.00",
            "description": "Popular mid-tier investment option"
        },
        {
            "name": "Silver",
            "investment": "R400.00",
            "duration": "6 days", 
            "return": "R800.00",
            "description": "Silver investment plan with an enhanced return."
        },
        {
            "name": "Momentum",
            "investment": "R800.00",
            "duration": "7 days",
            "return": "R1600.00",
            "description": "Build momentum with this high-value return plan for Level 2 investors."
        },
        {
            "name": "Booster Pack",
            "investment": "R1000.00",
            "duration": "9 days",
            "return": "R2000.00",
            "description": "A fast-paced plan for Level 2 users to boost their returns."
        },
        {
            "name": "Tier Breaker",
            "investment": "R1500.00",
            "duration": "10 days",
            "return": "R3000.00",
            "description": "Break through to higher returns"
        },
        {
            "name": "Power Ladder",
            "investment": "R2500.00",
            "duration": "12 days",
            "return": "R5000.00",
            "description": "Climb the ladder to significant returns"
        },
        {
            "name": "10K Sprint",
            "investment": "R5000.00",
            "duration": "14 days",
            "return": "R10000.00",
            "description": "Sprint to the 10K milestone"
        }
    ],
    
    "investment_rules": {
        "reinvestment_policy": "Users CANNOT reinvest in the same tier they are currently in. They must keep growing and move to higher tiers.",
        "growth_requirement": "To continue investing, users must progress to the next tier or higher.",
        "tier_progression": "Investment progression follows: Big Jumbo → Big Fish → Silver → Momentum → Booster Pack → Tier Breaker → Power Ladder → 10K Sprint",
        "minimum_progression": "Each new investment must be in a tier higher than the user's current active investment.",
        "investment_amounts": "Users can invest any amount they want, as long as they don't reinvest in the same tier. The tier amounts shown are examples, but users are free to invest any amount in higher tiers."
    },
    
    "referral_program": {
        "description": "Get R10 for every real user who signs up and deposits.",
        "referral_link": "https://safechain-7o0q.onrender.com/register/?ref=Shadow",
        "top_referrers": [
            {"name": "John S.", "earnings": "R25,000"},
            {"name": "Sarah M.", "earnings": "R18,500"},
            {"name": "Michael T.", "earnings": "R12,750"}
        ]
    },
    
    "how_it_works": [
        {
            "step": "AI-Powered Selection",
            "description": "Our AI analyzes market data to select low-risk crypto tokens with high potential.",
            "icon": "🤖"
        },
        {
            "step": "Automated Trading", 
            "description": "Trades are executed automatically and secured with advanced encryption.",
            "icon": "⚡"
        },
        {
            "step": "Profit Sharing",
            "description": "You earn returns based on the profits generated by our AI trading system.",
            "icon": "💰"
        }
    ],
    
    "testimonials": [
        {
            "rating": "★★★★★",
            "comment": "I turned R50 into R75 in just 7 days. This platform works!",
            "author": "John D."
        },
        {
            "rating": "★★★★★", 
            "comment": "The AI trading system is impressive. My investments are growing steadily.",
            "author": "Sarah M."
        },
        {
            "rating": "★★★★★",
            "comment": "Best crypto investment platform I've used. The returns are consistent.",
            "author": "Michael T."
        }
    ],
    
    "features": [
        "Secure payments",
        "Advanced AI",
        "Automated trading",
        "Low-risk crypto tokens",
        "Profit sharing",
        "Referral rewards",
        "Weekly updates",
        "AI investment tips"
    ],
    
    "support_info": {
        "minimum_investment": "R50",
        "currency": "R (South African Rand)",
        "platform_type": "AI-powered crypto investment",
        "security": "Advanced encryption",
        "automation": "Fully automated trading",
        "transparency": "Clear profit sharing model"
    },
    
    "investment_calculator": {
        "title": "Investment Calculator",
        "investment_amount_label": "Investment Amount (R)",
        "investment_amount_placeholder": "e.g., 500",
        "select_tier_label": "Select Tier",
        "expected_returns_label": "Expected Returns",
        "duration_label": "Duration",
        "return_date_label": "Return Date",
        "example_calculation": {
            "tier": "Big Jumbo",
            "investment": "R500.00",
            "expected_return": "R100.00",
            "duration": "1 days",
            "return_date": "2025-06-19"
        }
    },
    "cryptovault_how_it_works": """How CryptoVault Works 💼🪙\n\nSign Up: Create a free account here 👉 <a href=\"https://safechain-7o0q.onrender.com/\" target=\"_blank\">https://safechain-7o0q.onrender.com/</a>\n\nChoose a Plan: Start investing from just R50. Each plan has a set duration and return (e.g., invest R200 and get R400 in 5 days).\n\nMake a Deposit: Upload proof of payment (EFT or cash deposit). Once approved, your wallet gets funded.\n\nInvest: Use the funds in your wallet to activate any plan that fits your level.\n\nEarn Profits: Watch your money grow! You'll get your returns when the plan matures.\n\nWithdraw or Reinvest: Cash out your profits or reinvest to earn even more. 🎯\n\nRefer & Earn: Share your referral link and earn bonuses when your friends invest. 🔗💰""",
    "cryptovault_investment_tiers": """🪙 Crypto Vault AI Investment Tiers
Start building your financial future with one of our trusted plans. Choose based on your budget and earning goals:

🟢 Big Jumbo
💵 Investment: R50
🕒 Duration: 1 Day
💰 Return: R100
🔓 Perfect for beginners testing the platform

🟡 Big Fish
💵 Investment: R200
🕒 Duration: 5 Days
💰 Return: R400
⚡ Double your money in under a week

🔘 Silver
💵 Investment: R400
🕒 Duration: 6 Days
💰 Return: R800
🌟 Silver-tier plan with enhanced return rates

🔵 Momentum
💵 Investment: R800
🕒 Duration: 7 Days
💰 Return: R1600
🚀 Ideal for Level 2 investors building real momentum

🟣 Booster Pack
💵 Investment: R1000
🕒 Duration: 9 Days
💰 Return: R2000
⚙ Fast-paced growth strategy for active investors

🔴 Tier Breaker
💵 Investment: R1500
🕒 Duration: 10 Days
💰 Return: R3000
🧱 Break into the next level of earning power

🟠 Power Ladder
💵 Investment: R2500
🕒 Duration: 12 Days
💰 Return: R5000
🪜 Climb higher with long-term profit potential

🏁 10K Sprint
💵 Investment: R5000
🕒 Duration: 14 Days
💰 Return: R10000
🏆 Our highest-tier plan for top investors

💡 Use our Investment Calculator on the dashboard to see your expected return and return date instantly.

Need help choosing a plan or making a deposit? Chat with us — we're here to guide you every step of the way. 💬💼

🔗 Sign Up: <a href=\"https://safechain-7o0q.onrender.com\" target=\"_blank\">https://safechain-7o0q.onrender.com</a>""",
    "cryptovault_visual_onboarding": """
<h3>How CryptoVault Works: Step-by-Step Guide 🛡️</h3>
<ol>
  <li><b>Sign Up</b>: <a href=\"https://safechain-7o0q.onrender.com/\" target=\"_blank\">Create a free account</a> to get started. <span>📝</span></li>
  <li><b>Dashboard Overview</b>: After login, your dashboard shows your wallet balance, active investments, and quick actions. <span>📊</span></li>
  <li><b>Choose a Plan</b>: Pick an investment tier that fits your budget and goals. Plans start from <b>R50</b> and go up to <b>R5000</b>. <span>🪙</span></li>
  <li><b>Make a Deposit</b>: Upload proof of payment (EFT or cash deposit) using the <b>Upload POP</b> button. <span>📎</span></li>
  <li><b>Invest</b>: Use your funded wallet to activate a plan. Each plan shows its duration and expected return. <span>🚀</span></li>
  <li><b>Track Progress</b>: Watch your investment grow on your dashboard. You'll see your plan status and return date. <span>⏳</span></li>
  <li><b>Withdraw or Reinvest</b>: When your plan matures, withdraw your profits or reinvest in a higher tier. <span>💸</span></li>
  <li><b>Refer & Earn</b>: Share your referral link to earn bonuses when friends invest. <span>🔗💰</span></li>
</ol>
<p><b>Tip:</b> All these steps are visualized on your dashboard after login. If you need help, just ask!</p>
"""
}

# Common questions and their answers
SAFECHAIN_FAQ = {
    "investment_minimum": {
        "question": "What is the minimum investment?",
        "answer": "The minimum investment starts from just R50."
    },
    "investment_amounts": {
        "question": "Can I invest any amount I want?",
        "answer": "Yes, you can invest any amount you want, as long as you don't reinvest in the same tier. The tier amounts shown (R50, R200, R400, etc.) are examples, but you are free to invest any amount in higher tiers. The key rule is: no reinvestment in the same tier - you must keep growing to higher tiers."
    },
    "investment_duration": {
        "question": "How long do investments take?",
        "answer": "Investment durations range from 1 day to 14 days depending on the tier you choose."
    },
    "returns": {
        "question": "What returns can I expect?",
        "answer": "Returns range from R100 for 1-day investments to R10,000 for 14-day investments, depending on the tier."
    },
    "reinvestment_policy": {
        "question": "Can I reinvest in the same tier?",
        "answer": "No, you cannot reinvest in the same tier. You must keep growing and move to higher tiers. The progression is: Big Jumbo → Big Fish → Silver → Momentum → Booster Pack → Tier Breaker → Power Ladder → 10K Sprint."
    },
    "tier_progression": {
        "question": "How does tier progression work?",
        "answer": "Each new investment must be in a tier higher than your current active investment. This ensures continuous growth and prevents users from staying in the same tier."
    },
    "security": {
        "question": "Is my investment secure?",
        "answer": "Yes, all trades are executed automatically and secured with advanced encryption."
    },
    "ai_trading": {
        "question": "How does the AI trading work?",
        "answer": "Our AI analyzes market data to select low-risk crypto tokens with high potential, then executes trades automatically."
    },
    "referrals": {
        "question": "How do referrals work?",
        "answer": "You get R10 for every real user who signs up and deposits using your referral link."
    },
    "registration": {
        "question": "How do I register?",
        "answer": "You can register at https://safechain-7o0q.onrender.com/register/?ref=Shadow"
    }
}

# Support categories for ticket classification
SAFECHAIN_SUPPORT_CATEGORIES = {
    "investment_questions": "Questions about investment tiers, returns, and duration",
    "technical_support": "Platform access, login issues, or technical problems", 
    "payment_issues": "Deposit problems, withdrawal issues, or payment verification",
    "referral_program": "Questions about the referral system and rewards",
    "account_management": "Profile updates, account settings, or personal information",
    "general_inquiry": "General questions about SafeChain AI services"
}

# Priority levels for different types of issues
SAFECHAIN_PRIORITY_GUIDE = {
    "high": [
        "Payment verification issues",
        "Account access problems", 
        "Investment withdrawal requests",
        "Security concerns"
    ],
    "medium": [
        "Investment tier questions",
        "Referral program inquiries",
        "General platform questions"
    ],
    "low": [
        "General information requests",
        "Feature inquiries",
        "Feedback and suggestions"
    ]
} 